### PR TITLE
[Problem#10] Find Peak Element - Please review

### PR DESCRIPTION
**Pull request by SibirajanSadhasivam**

### CODE REVIEW

**Comment by SibirajanSadhasivam** [comment]
04/01 - [Problem#7](https://github.com/super30admin/Binary-Search-1/pull/1081), [Problem#8](https://github.com/super30admin/Binary-Search-1/pull/1082) and [Problem#10](https://github.com/super30admin/Binary-Search-1/pull/1083)

**Comment by SibirajanSadhasivam** [comment]
Created the PR in wrong repo. Closing.

**Review by brunda4 — COMMENTED** [review]
Please complete both the problems.

**Comment by brunda4** [comment]
Please complete all the problems.

**Pull request closed without merging**
